### ISSUE TITLE
iOS ?

### ISSUE THREAD

**Issue by grallc** [ionic-team/demo-capacitor-mapbox#1]
Hello,
Thanks for the demo !
Is it planned to provide an iOS version of the plugin ?

**Comment by dotNetkow** [comment]
Since this is just a reference demo, I wasn't planning on it. 

The process would be similar: integrate the [Mapbox iOS SDK](https://docs.mapbox.com/ios/maps/overview/), then follow along with the [Capacitor iOS plugin guide](https://capacitor.ionicframework.com/docs/plugins/ios).
